version: '3.8'

services:
  # -----------------------------------------------------------------
  # 1. TRAEFIK ( The Gateway )
  # -----------------------------------------------------------------
  traefik:
    image: traefik:v3.6
    container_name: vortex-traefik
    restart: always
    command:
      # Global Settings
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--log.level=INFO"

      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      
      # Certificate Resolver (LetsEncrypt)
      - "--certificatesresolvers.myresolver.acme.email=sangwanhimanshu8443@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # Use HTTP Challenge
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      
      # Provider 1: Docker (For User Apps)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=vortex-net"

      # Provider 2: File (For Dashboard Domain Updates)
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only access to Docker
      - ${DATA_DIR:-./data}/ssl:/letsencrypt
      - ${DATA_DIR:-./data}/traefik:/etc/traefik/dynamic
    networks:
      - vortex-net

  # -----------------------------------------------------------------
  # 2. Web App
  # -----------------------------------------------------------------
  dashboard:
    build:
      context: .
      dockerfile: dockerfile
    container_name: vortex-dashboard
    privileged: true
    ports:
      - "8443:3000"
    restart: always
    environment:
      - DATABASE_URL=file:/app/data/db.sqlite
      - NODE_ENV=production
      - TRAEFIK_CONFIG_DIR=/app/traefik-config
      - BUILDKIT_HOST=tcp://vortex-buildkit:1234
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR:-./data}/db:/app/data
      - ${DATA_DIR:-./data}/traefik:/app/traefik-config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.localhost`)"
      - "traefik.http.services.dashboard.loadbalancer.server.port=3000"
    networks:
      - vortex-net
    dns:
      - 8.8.8.8
      - 1.1.1.1
      
  buildkit:
    image: moby/buildkit:latest
    container_name: vortex-buildkit
    restart: always
    privileged: true
    command: --addr tcp://0.0.0.0:1234
    entrypoint:
      - buildkitd
    ports:
      - "1234:1234"
    networks:
      - vortex-net

networks:
  vortex-net:
    name: vortex-net
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: vortex-bridge

volumes:
  vortex-traefik-config: